import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
/* ToastContainer */
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MainContextProvider from "@/context/MainContext";
import SWRProvider from "@/swr/SWRProvider";
import { getAppInfo } from "@/api/getAppInfo";




export const metadata = {
  title: "Electronics",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const appInfo = await getAppInfo();

  return (
    <html lang="en">
      <body>
        <SWRProvider>
          <MainContextProvider>
              <Header appInfo={appInfo} />
              {children}
              <Footer appInfo={appInfo} />
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
          </MainContextProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
